#!/usr/bin/env bash
# This script installs and configures Nginx to listen on port 80 and return "Hello World".
apt-get -y update
apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart