#!/usr/bin/env bash
# Bash script that will double the number of webservers I have.
apt-get -y update
apt-get -y upgrade
apt-get -y install nginx
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html /etc/nginx/html/404.html
echo "Hello World!" > /etc/nginx/html/index.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html
printf %s "server {
    listen  80 default_server;
    listen  [::]:80 default_server;
    root    /etc/nginx/html;
    index   index.html;
    add_header X-Served-By $HOSTNAME;
    location /redirect_me {
        return 301;
    }
    error_page 404 /404.html;
    location /404 {
      root /etc/nginx/html;
      internal;
    }
}" > /etc/nginx/sites-available/default
service nginx restart